services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post2222sql
    ports:
      - 5432:5432
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - externe

volumes:
  keycloak-postgres-data:

networks:
  externe:
    external: true
