services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post2222sql
    ports:
      - 5432:5432
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - my_network:
          -ipv4_address: 127.25.128.5

volumes:
  keycloak-postgres-data:

networks:
  my_network:
    ipam:
      config:
        -subnet: 172.25.128.0/24
